import { type NextPage } from "next";
import { useState } from "react";
import NavBar from "~/components/NavBar";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Quotes: NextPage = () => {
  const quotes = api.quote.getAll.useQuery();
  console.log(quotes.data);
  return (
    <>
      <Head>
        <title>Quotes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1>All Quotes</h1>
        {quotes.data?.map((quote) => {
          return (
            <a
              key={quote.id}
              href="#"
              className="min-h-44 block max-w-sm rounded-lg border border-gray-200 bg-white p-6 shadow hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700"
            >
              <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                {quote.text}
              </h5>
              <p className="font-normal text-gray-700 dark:text-gray-400">
                {quote.author}
              </p>
            </a>
          );
        })}
      </main>
    </>
  );
};

export default Quotes;
